# -*- coding: utf-8 -*-
"""SETUP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWdnDhKjU_bR0EMh9NT91VC7HJ1pEp8v
"""

from setuptools import setup, find_packages

setup(
    name="Topsis-Kunal-102303827",
    version="1.0",
    author="Kunal Dahiya",
    packages=find_packages(),
    install_requires=["pandas", "numpy"],
    entry_points={
        "console_scripts": [
            "topsis=topsis.topsis:main"
        ]
    }
)